pricing:
  default_anchor: 256
  alpha: 0.35
  sell_spread: 0.80

weekly:
  items: []

storage:
  mode: FLATFILE
  mysql:
    host: localhost
    port: 3306
    database: playermarket
    username: root
    password: ""
    useSsl: false
    tablePrefix: pm_

importer:
  enabled: true
  mode: FILE
  file: data/base-prices.yml
