name: PlayerMarket
main: xyz.rcfg.playermarket.PlayerMarketPlugin
version: 0.7.5
api-version: '1.21'
softdepend: [Vault]
commands:
  shop: {description: Open the player market, usage: /shop}
  pm:   {description: PlayerMarket admin, usage: /pm <reloadcats|rebuildcats|exportprices|loadandfill|sellall>, permission: playermarket.admin}
  sellall: {description: Open SellAll GUI, usage: /sellall}
permissions:
  playermarket.admin: {default: op}
