name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build
        run: mvn -B -U -q -DskipTests=false clean package
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: player-market-${{ github.ref_name }}
          path: |
            target/*.jar
            target/*.pom
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
